//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_EFM2018_V1_1.ServiceReferenceCapacite {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCapacite.WebServiceVerifCapaciteSoap")]
    public interface WebServiceVerifCapaciteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Capacite", ReplyAction="*")]
        bool Capacite(int idSalle, int idEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Capacite", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CapaciteAsync(int idSalle, int idEvent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceVerifCapaciteSoapChannel : WebApp_EFM2018_V1_1.ServiceReferenceCapacite.WebServiceVerifCapaciteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceVerifCapaciteSoapClient : System.ServiceModel.ClientBase<WebApp_EFM2018_V1_1.ServiceReferenceCapacite.WebServiceVerifCapaciteSoap>, WebApp_EFM2018_V1_1.ServiceReferenceCapacite.WebServiceVerifCapaciteSoap {
        
        public WebServiceVerifCapaciteSoapClient() {
        }
        
        public WebServiceVerifCapaciteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceVerifCapaciteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceVerifCapaciteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceVerifCapaciteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Capacite(int idSalle, int idEvent) {
            return base.Channel.Capacite(idSalle, idEvent);
        }
        
        public System.Threading.Tasks.Task<bool> CapaciteAsync(int idSalle, int idEvent) {
            return base.Channel.CapaciteAsync(idSalle, idEvent);
        }
    }
}
